pref("extensions.{10228D1E-6D25-4ccc-903E-272D66EEC763}.description", "chrome://show_location/locale/show_location.properties");
pref('show_location.onload_timedelay', 250);
pref('show_location.servertime_interval', 30000);
pref('show_location.hide_toolmenu_iptool', false);
pref('show_location.hide_toolmenu_maptool', false);
pref('show_location.hide_rightclick_showiptool', false);
pref('show_location.hide_rightclick_showmap', false);
pref('show_location.db_checked_CZ', true);
pref('show_location.CZ_type', 0);
pref('show_location.GEO_type', 0);
pref('show_location.maptool_lang', 0);
pref('show_location.maptool_googlebar', false);
pref('show_location.db_checked_GEO', true);
pref('show_location.db_path_CZ', "QQWry.Dat");
pref('show_location.db_path_GEO', "GeoLiteCity.dat");
pref('show_location.status_minwidth', 0);
pref('show_location.status_maxwidth', 999);
pref('show_location.status_position', 1);
pref('show_location.statusbox_position', "status-bar, 999");
pref('show_location.status_color', "#000000");
pref('show_location.tooltip_color', "#000000");
pref('show_location.style_status_list', "CZ0, G07, G08, G02, AFL");
pref('show_location.style_tooltip_list', "G07, G09, G04, IP0, TM0, ST0");
pref('show_location.enable_tooltip', true);
pref('show_location.urlbar_focus_hide', true);